# Generated by Django 5.0.2 on 2024-03-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('symbol', models.CharField(blank=True, max_length=256)),
                ('industry', models.CharField(blank=True, max_length=256)),
                ('isinCode', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
